config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'bookmarks/create'

  resources :links, only: %i[index create destroy show]
  get 'logins/new'
  get 'logins/index'
  get 'logins/callbacks', to: 'logins/callbacks#create'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'links#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  include ActionView::RecordIdentifier

  primary_abstract_class
end

app/models/concerns/url_validator.rb
# frozen_string_literal: true

class UrlValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    uri = URI.parse(value)

    raise 'not a valid url' unless uri.is_a?(URI::HTTPS)
  rescue StandardError
    record.errors.add attribute, 'is not a valid URL'
  end
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :user

  validates :url, presence: true, url: true
  validates :url, uniqueness: { scope: :user_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true

  has_many :links, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ActionView::RecordIdentifier

  before_action :require_identity

  def render_flash_error(error)
    flash.now[:error] = error
    render turbo_stream: turbo_stream.update('flash', partial: 'shared/flash')
  end

  private

  def require_identity
    redirect_to logins_index_path unless User.exists?(identity: session[:identity])
  end
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

class BookmarksController < ApplicationController
  def create
    Link.create!(url: params[:url], user:)

    redirect_to root_path
  end

  private

  def user
    User.find_by!(identity: session[:identity])
  end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  def index
    render locals: { links: user.links.order(created_at: :desc), user: }
  end

  def show
    render locals: { user:, link: user.links.find(params[:id]), title: 'Loading...' }
  end

  def create
    link = Link.new(create_params.merge(user:))
    return render locals: { link: } if link.save

    render_flash_error(link.errors.full_messages.join(', ').strip)
  end

  def destroy
    link = user.links.find(params[:id])
    return render locals: { link: } if link.destroy

    render_flash_error(link.errors.full_messages.join(', ').strip)
  end

  private

  def create_params
    params.require(:link).permit(:url)
  end

  def user
    User.find_by!(identity: session[:identity])
  end
end

app/controllers/logins/callbacks_controller.rb
# frozen_string_literal: true

module Logins
  class CallbacksController < ApplicationController
    skip_before_action :require_identity
    before_action :validate_state
    before_action :reset_session

    def create
      id_token = TokenExchanger.exchange_code(code: params[:code])

      return head :bad_request unless User.exists?(email: id_token['email'])

      session[:identity] = User.find_by(email: id_token['email']).identity

      redirect_to root_path
    end

    private

    def validate_state
      session_state = session.delete(:state)
      return if session_state.present? && params[:state].present? && session_state == params[:state]

      reset_session
      head :bad_request
    end
  end
end

app/controllers/logins_controller.rb
# frozen_string_literal: true

class LoginsController < ApplicationController
  skip_before_action :require_identity
  before_action :reset_session

  def index; end

  def new
    session[:state] = SecureRandom.uuid
    redirect_to redirect_uri, allow_other_host: true
  end

  private

  def redirect_uri
    URI.parse('https://accounts.google.com/o/oauth2/v2/auth').tap do |uri|
      uri.query = URI.encode_www_form([
                                        %w[response_type code],
                                        ['client_id', Rails.application.credentials.google.client_id],
                                        ['scope', 'openid email'],
                                        ['redirect_uri',
                                         Rails.application.routes.url_helpers.logins_callbacks_url(host: 'http://localhost:3000')],
                                        ['state', session[:state]]
                                      ])
    end.to_s
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# main app helper
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
# frozen_string_literal: true

module BookmarksHelper
end

app/helpers/login/callback_helper.rb
# frozen_string_literal: true

module Login
  module CallbackHelper
  end
end

app/helpers/login_helper.rb
# frozen_string_literal: true

module LoginHelper
end

app/helpers/material_form_builder.rb
# frozen_string_literal: true

class MaterialFormBuilder < ActionView::Helpers::FormBuilder
  delegate :tag, :button_tag, to: :template

  # rubocop:disable Metrics/AbcSize
  # rubocop:disable Metrics/MethodLength
  def text_field(method, options = {})
    label_classes = String(options[:class]).split + ['mdc-text-field', 'mdc-text-field--filled']
    input_clasess = String(options[:class]).split + ['mdc-text-field__input']

    options.except!(:class)

    label = options.delete(:label) || method.to_s.titleize

    # Fix for known Safari bug, https://github.com/material-components/material-components-web/issues/5879
    options[:placeholder] = options[:placeholder] || ' '

    tag.label(class: label_classes.compact.uniq.join(' ').strip) do
      tag.span(class: 'mdc-text-field__ripple') +
        tag.span(class: 'mdc-floating-label', id: options[:id]) { label } +
        super(method, options.merge(class: input_clasess.compact.uniq.join(' '))) +
        tag.span(class: 'mdc-line-ripple')
    end
  end

  def button(value = nil, options = {}, &block)
    classes = String(options[:class]).split + ['mdc-button', 'mdc-button--touch']
    options[:class] = classes.compact.uniq.join(' ').strip

    tag.div(class: 'mdc-touch-target-wrapper') do
      button_tag(nil, options) do
        tag.span(class: 'mdc-button__ripple') +
          tag.span(class: 'mdc-button__touch') +
          tag.span(class: 'mdc-button__label') do
            block ? block.call : value
          end
      end
    end
  end
  # rubocop:enable Metrics/MethodLength
  # rubocop:enable Metrics/AbcSize

  private

  attr_reader :template
end

app/helpers/material_tags_helper.rb
# frozen_string_literal: true

module MaterialTagsHelper
  def material_button_tag(text, controllers: [], actions: [])
    controllers = (controllers + ['material-tags']).uniq.join(' ')

    tag.div(class: 'mdc-touch-target-wrapper', data: { controller: controllers, action: actions.uniq.join(' ') }) do
      content_tag(:button, { class: 'mdc-button mdc-button--raised mdc-button--touch' }) do
        tag.span(class: 'mdc-button__ripple') +
          tag.span(class: 'mdc-button__touch') +
          tag.span(class: 'mdc-button__label') do
            text
          end
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Media Mail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Material+Icons|Roboto+Slab">
    <link href="https://unpkg.com/material-components-web@v13.0.0/dist/material-components-web.min.css" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <div id="flash">
        <%= render 'shared/flash' %>
      </div>
      <%= yield %>
    </main>

  </body>
</html>

app/views/links/_form.html.erb
<div class="mb-4" id="form">
  <%= form_with model: Link.new, builder: MaterialFormBuilder, data: { controller: "material-form" }, html: { class: "flex flex-row gap-6 items-center" } do |f| %>
    <%= f.text_field :url, class: "grow", label: "URL" %>
    <%= f.button "Submit", type:"submit", class: "mdc-button--raised" %>
  <% end %>
</div>

app/views/links/_link.html.erb
<div class="mdc-card mdc-card--outlined max-w-md" id=<%= dom_id(link) %>>
  <div class="p-[16px]">
    <%= link_to link.url, link_path(link) %>
  </div>
  <div class="mdc-card__actions">
    <%= form_with model: link, builder: MaterialFormBuilder, method: :delete, data: { controller: "material-form" }, html: { class: "inline mdc-card__action" } do |f| %>
      <%= f.button "Delete", type:"submit", class: "mdc-card__action mdc-card__action--button" %>
    <% end %>
  </div>
</div>

app/views/links/_page.html.erb
<div id="<%= dom_id(link, :page) %>" data-controller='pages' data-pages-content-value="<%= content %>">
  <h1 class="text-xl"><%= title %></h1>
  <div content class="leading-relaxed text-lg font-serif"></div>
</div>

app/views/links/create.turbo_stream.erb
<%= turbo_stream.append(:links, partial: 'links/link', locals: { link: }) %>
<%= turbo_stream.replace(:form, partial: 'links/form') %>

app/views/links/destroy.turbo_stream.erb
<%= turbo_stream.remove(link) %>

app/views/links/index.html.erb
<%= render partial: 'form' %>

<div id="links" class="flex flex-row flex-wrap items-start gap-2">
  <%= render links %>
</div>

<%= turbo_stream_from user.identity, :links, channel: LinksChannel %>

app/views/links/show.html.erb
<%= turbo_stream_from user.identity, [:page, link.id], channel: PageChannel %>

<div class="flex flex-row w-full justify-center">
  <%= render partial: 'page', locals: { user:, link:, content: '<script><p>test</p></script><p>test</p>', title: 'Loading...' } %>
</div>

app/views/logins/index.html.erb
<div class="text-center">
  <%= material_button_tag "Login", controllers: ['login'], actions: ['click->login#login'] %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <% if type == "error" %>
    <aside class="mdc-snackbar" data-controller="flash">
      <div class="mdc-snackbar__surface" role="status" aria-relevant="additions">
        <div class="mdc-snackbar__label" aria-atomic="false">
          <%= message %>
        </div>
        <div class="mdc-snackbar__actions" aria-atomic="true">
          <button type="button" class="mdc-button mdc-snackbar__action">
            <div class="mdc-button__ripple"></div>
            <span class="mdc-button__label">Close</span>
          </button>
        </div>
      </div>
    </aside>
  <% end %>
<% end %>